version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "5175:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: